Joe=(input("Joe birthday:"))
Tom=(input("Tom birthday:"))
Tim=(input("Tim birthday"))
Bob=(input("Bob birthday:"))
John=(input("John birthday:"))
print("\nJoes birthday is",Joe)
print("Toms birthday is",Tom)
print("Tims birthday is",Tim)
print("Bobs birthday is",Bob)
print("Johns birthday is",John)